import { DanceClass, Teacher } from './types';

export const DANCE_STYLES = [
  'Acroverticales', 'Bachata', 'Ballet', 'Breakdance', 'Cha-cha-chá',
  'Contemporáneo', 'Dancehall', 'Folklore', 'Heels', 'Hip Hop',
  'House', 'Jazz', 'Jazz Funk', 'K-pop', 'Reggaetón',
  'Salsa', 'Tango', 'Urbano', 'Zumba',
];

export const LEVELS = ['Inicial', 'Básico', 'Intermedio', 'Avanzado', 'Todos los niveles'];
export const CITIES = ['Lima', 'Arequipa', 'Cusco', 'Trujillo', 'Piura'];
export const LIMA_DISTRICTS = [
  'Miraflores', 'San Isidro', 'Barranco', 'Surco', 'San Borja',
  'La Molina', 'Jesús María', 'Lince', 'Magdalena', 'San Miguel',
  'Pueblo Libre', 'Chorrillos', 'Villa María del Triunfo',
];

export const mockTeachers: Teacher[] = [
  {
    id: 't1',
    name: 'Academia Ritmo Latino',
    type: 'academia',
    photo: 'https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=400&q=80',
    city: 'Lima',
    district: 'Miraflores',
    bio: 'Academia especializada en bailes latinos con más de 10 años formando bailarines en Lima.',
    experience: 10,
    styles: ['Salsa', 'Bachata', 'Cha-cha-chá'],
    whatsapp: '+51987654321',
    email: 'contacto@ritmolatinoac.com',
    instagram: '@ritmolatinoac',
    tiktok: '@ritmolatinoac',
    rating: 4.8,
    totalClasses: 12,
  },
  {
    id: 't2',
    name: 'Sofía Vega',
    type: 'profesor',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    city: 'Lima',
    district: 'Barranco',
    bio: 'Coreógrafa y profesora de Heels y Jazz Funk. He bailado en escenarios internacionales.',
    experience: 7,
    styles: ['Heels', 'Jazz Funk', 'Jazz'],
    whatsapp: '+51912345678',
    email: 'sofia.vega@gmail.com',
    instagram: '@sofiavegadance',
    tiktok: '@sofiavegadance',
    rating: 4.9,
    totalClasses: 5,
  },
  {
    id: 't3',
    name: 'Studio Urbano',
    type: 'academia',
    photo: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    city: 'Lima',
    district: 'Surco',
    bio: 'Estudio dedicado a los estilos urbanos: Hip Hop, Breakdance y Reggaetón.',
    experience: 5,
    styles: ['Hip Hop', 'Breakdance', 'Reggaetón', 'Urbano'],
    whatsapp: '+51998765432',
    email: 'hola@studiourbano.pe',
    instagram: '@studiourbano',
    rating: 4.7,
    totalClasses: 8,
  },
  {
    id: 't4',
    name: 'María Elena Quispe',
    type: 'profesor',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    city: 'Lima',
    district: 'Jesús María',
    bio: 'Maestra de Ballet Clásico y Contemporáneo graduada del Instituto Nacional Superior de Folklore.',
    experience: 15,
    styles: ['Ballet', 'Contemporáneo'],
    whatsapp: '+51975432198',
    email: 'maria.quispe@ballet.pe',
    rating: 5.0,
    totalClasses: 6,
  },
];

export const mockClasses: DanceClass[] = [
  {
    id: 'c1',
    type: 'clase',
    title: 'Salsa Básico desde cero',
    style: 'Salsa',
    level: 'Básico',
    shortDescription: 'Aprende los pasos básicos de salsa en un ambiente divertido y profesional.',
    fullDescription: 'En esta clase aprenderás los fundamentos de la salsa cubana: paso básico, giros, tempo y conexión con tu pareja. El ambiente es amigable y el ritmo es tuyo.',
    whatYouLearn: ['Paso básico on1 y on2', 'Giros básicos', 'Conexión con pareja', 'Musicality'],
    forWhom: 'Personas sin experiencia previa que quieren aprender a bailar salsa desde cero.',
    requirements: 'Sin experiencia previa necesaria.',
    startDate: '2026-06-02',
    timeSlots: [
      { days: ['Lunes', 'Miércoles'], startTime: '19:00', endTime: '20:30' },
    ],
    priceType: 'Mensual',
    price: 180,
    currency: 'PEN',
    maxSpots: 20,
    availableSpots: 8,
    reservationMode: 'whatsapp',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Miraflores',
    address: 'Av. Benavides 1234, piso 3',
    reference: 'Frente al parque Kennedy',
    mapsUrl: 'https://maps.google.com',
    lat: -12.1219,
    lng: -77.0300,
    coverImage: 'https://images.unsplash.com/photo-1545959570-a94084071b5d?w=800&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    footwear: 'Zapatos de salsa o zapatillas',
    clothing: 'Ropa cómoda y transpirable',
    toBring: ['Agua', 'Toalla'],
    ageGroup: 'Adultos',
    status: 'active',
    teacher: mockTeachers[0],
    contacts: 34,
    createdAt: '2026-05-01',
  },
  {
    id: 'c2',
    type: 'taller',
    title: 'Heels Intermedio con Sofía Vega',
    style: 'Heels',
    level: 'Intermedio',
    shortDescription: 'Taller intensivo de heels para quienes ya tienen base. Potencia tu fuerza y sensualidad.',
    fullDescription: 'Este taller está diseñado para bailarinas que ya tienen una base en heels y quieren llevar su técnica al siguiente nivel. Trabajaremos floorwork, giros y performance.',
    whatYouLearn: ['Floorwork avanzado', 'Giros en tacones', 'Construcción de performance', 'Expresión corporal'],
    forWhom: 'Bailarinas con experiencia previa en heels o al menos 6 meses bailando.',
    requirements: 'Experiencia previa en baile.',
    startDate: '2026-06-14',
    endDate: '2026-06-14',
    timeSlots: [
      { days: ['Sábado'], startTime: '10:00', endTime: '13:00' },
    ],
    priceType: 'Precio único',
    price: 120,
    currency: 'PEN',
    maxSpots: 15,
    availableSpots: 3,
    reservationMode: 'direct',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Barranco',
    address: 'Jr. Ayacucho 456',
    lat: -12.1494,
    lng: -77.0211,
    coverImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    footwear: 'Tacos / heels (mínimo 5 cm)',
    clothing: 'Outfit de baile',
    toBring: ['Agua', 'Rodilleras'],
    ageGroup: 'Adultos',
    status: 'active',
    teacher: mockTeachers[1],
    contacts: 21,
    createdAt: '2026-05-05',
  },
  {
    id: 'c3',
    type: 'curso',
    title: 'Hip Hop Freestyle – Nivel Básico',
    style: 'Hip Hop',
    level: 'Básico',
    shortDescription: 'Curso mensual de Hip Hop donde aprenderás grooves, footwork y freestyle básico.',
    fullDescription: 'Este curso te da las herramientas para expresarte con el Hip Hop. Desde los grooves fundamentales hasta tu primer freestyle, semana a semana construirás confianza y estilo.',
    whatYouLearn: ['Groove y bounce', 'Footwork básico', 'Cypher etiquette', 'Freestyle básico'],
    startDate: '2026-06-01',
    timeSlots: [
      { days: ['Martes', 'Jueves'], startTime: '18:00', endTime: '19:30' },
      { days: ['Sábado'], startTime: '12:00', endTime: '13:30' },
    ],
    priceType: 'Mensual',
    price: 160,
    currency: 'PEN',
    maxSpots: 25,
    availableSpots: 15,
    reservationMode: 'whatsapp',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Surco',
    address: 'Av. Caminos del Inca 890',
    lat: -12.1398,
    lng: -76.9876,
    coverImage: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&q=80',
    footwear: 'Zapatillas',
    clothing: 'Ropa cómoda y holgada',
    toBring: ['Agua', 'Toalla'],
    ageGroup: 'Todas las edades',
    status: 'active',
    teacher: mockTeachers[2],
    contacts: 18,
    createdAt: '2026-05-10',
  },
  {
    id: 'c4',
    type: 'masterclass',
    title: 'Masterclass de Ballet Clásico',
    style: 'Ballet',
    level: 'Intermedio',
    shortDescription: 'Una clase magistral con la maestra María Elena Quispe. Técnica pura y elegancia.',
    fullDescription: 'Sesión intensiva de técnica de ballet clásico: trabajo de barra, centre y variación. Para bailarines con base que quieren profundizar su técnica.',
    whatYouLearn: ['Trabajo de barra avanzado', 'Combinaciones al centro', 'Variación de repertorio clásico'],
    startDate: '2026-06-07',
    endDate: '2026-06-07',
    timeSlots: [
      { days: ['Domingo'], startTime: '09:00', endTime: '12:00' },
    ],
    priceType: 'Precio único',
    price: 150,
    currency: 'PEN',
    maxSpots: 12,
    availableSpots: 0,
    reservationMode: 'direct',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Jesús María',
    address: 'Av. Salaverry 2020',
    lat: -12.0863,
    lng: -77.0509,
    coverImage: 'https://images.unsplash.com/photo-1516737490857-848138f11e06?w=800&q=80',
    footwear: 'Zapatillas de ballet o medias de ballet',
    clothing: 'Maillot y medias',
    toBring: ['Agua', 'Mat'],
    ageGroup: 'Adolescentes',
    prerequisites: 'Conocimiento básico de ballet',
    status: 'full',
    teacher: mockTeachers[3],
    contacts: 12,
    createdAt: '2026-05-08',
  },
  {
    id: 'c5',
    type: 'clase',
    title: 'Bachata Sensual – Principiantes',
    style: 'Bachata',
    level: 'Inicial',
    shortDescription: 'Inicia tu camino en la bachata sensual. Ritmo, conexión y sensualidad desde cero.',
    fullDescription: 'Clases diseñadas para quienes nunca han bailado bachata. Aprenderás el ritmo, los pasos básicos y la conexión con pareja en un ambiente relajado y divertido.',
    startDate: '2026-06-03',
    timeSlots: [
      { days: ['Martes', 'Viernes'], startTime: '20:00', endTime: '21:30' },
    ],
    priceType: 'Mensual',
    price: 170,
    currency: 'PEN',
    maxSpots: 20,
    availableSpots: 12,
    reservationMode: 'whatsapp',
    modality: 'Presencial',
    city: 'Lima',
    district: 'San Borja',
    address: 'Av. Angamos Este 1547',
    lat: -12.1003,
    lng: -77.0000,
    coverImage: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800&q=80',
    footwear: 'Zapatos de salsa o sandalias con taco bajo',
    status: 'active',
    teacher: mockTeachers[0],
    contacts: 27,
    createdAt: '2026-05-12',
  },
  {
    id: 'c6',
    type: 'clase',
    title: 'Jazz Funk – Intermedios',
    style: 'Jazz Funk',
    level: 'Intermedio',
    shortDescription: 'Combina el jazz técnico con el groove funk. Clase dinámica y muy energética.',
    fullDescription: 'Jazz Funk para quienes ya tienen base en danza. Trabajaremos combinaciones de jazz con groove, ritmo y actitud funk. Cada clase aprenderás una nueva secuencia.',
    startDate: '2026-06-02',
    timeSlots: [
      { days: ['Lunes', 'Miércoles', 'Viernes'], startTime: '19:30', endTime: '21:00' },
    ],
    priceType: 'Mensual',
    price: 200,
    currency: 'PEN',
    maxSpots: 18,
    availableSpots: 6,
    reservationMode: 'whatsapp',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Barranco',
    address: 'Jr. Ayacucho 456',
    lat: -12.1494,
    lng: -77.0211,
    coverImage: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800&q=80',
    status: 'active',
    teacher: mockTeachers[1],
    contacts: 15,
    createdAt: '2026-05-15',
  },
  {
    id: 'c7',
    type: 'intensivo',
    title: 'Intensivo de Contemporáneo',
    style: 'Contemporáneo',
    level: 'Avanzado',
    shortDescription: 'Semana intensiva de danza contemporánea con enfoque en improvisación y composición.',
    fullDescription: 'Una semana intensa donde exploraremos los lenguajes del contemporáneo: improvisación contact, composición coreográfica y técnicas somáticas.',
    startDate: '2026-07-07',
    endDate: '2026-07-11',
    timeSlots: [
      { days: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'], startTime: '10:00', endTime: '14:00' },
    ],
    priceType: 'Precio único',
    price: 350,
    currency: 'PEN',
    maxSpots: 10,
    availableSpots: 4,
    reservationMode: 'request',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Barranco',
    address: 'Av. Pedro de Osma 135',
    lat: -12.1515,
    lng: -77.0219,
    coverImage: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=800&q=80',
    footwear: 'Pies descalzos',
    clothing: 'Ropa cómoda que permita movimiento amplio',
    toBring: ['Agua', 'Mat'],
    prerequisites: 'Experiencia previa en danza',
    status: 'active',
    teacher: mockTeachers[3],
    contacts: 8,
    createdAt: '2026-05-20',
  },
  {
    id: 'c8',
    type: 'clase',
    title: 'K-pop Dance – Básico',
    style: 'K-pop',
    level: 'Básico',
    shortDescription: 'Aprende las coreografías más populares del K-pop en un ambiente divertido y dinámico.',
    fullDescription: 'Clases semanales donde aprenderás covers de grupos como BTS, BLACKPINK, TWICE y más. No necesitas experiencia, solo ganas de bailar.',
    startDate: '2026-06-05',
    timeSlots: [
      { days: ['Viernes'], startTime: '18:00', endTime: '19:30' },
      { days: ['Sábado'], startTime: '11:00', endTime: '12:30' },
    ],
    priceType: 'Mensual',
    price: 140,
    currency: 'PEN',
    maxSpots: 30,
    availableSpots: 20,
    reservationMode: 'whatsapp',
    modality: 'Presencial',
    city: 'Lima',
    district: 'Surco',
    address: 'Av. Caminos del Inca 890',
    lat: -12.1398,
    lng: -76.9876,
    coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    footwear: 'Zapatillas cómodas',
    ageGroup: 'Adolescentes',
    status: 'active',
    teacher: mockTeachers[2],
    contacts: 45,
    createdAt: '2026-05-18',
  },
];

export function getStatusLabel(status: string): string {
  const map: Record<string, string> = {
    active: 'Disponible',
    draft: 'Borrador',
    paused: 'Pausada',
    finished: 'Finalizada',
    full: 'Sin cupos',
  };
  return map[status] || status;
}

export function getStatusColor(status: string): string {
  const map: Record<string, string> = {
    active: 'bg-green-100 text-green-700',
    draft: 'bg-gray-100 text-gray-600',
    paused: 'bg-yellow-100 text-yellow-700',
    finished: 'bg-gray-100 text-gray-500',
    full: 'bg-red-100 text-red-600',
  };
  return map[status] || 'bg-gray-100 text-gray-600';
}

export function getTypeLabel(type: string): string {
  const map: Record<string, string> = {
    clase: 'Clase',
    taller: 'Taller',
    curso: 'Curso',
    masterclass: 'Masterclass',
    intensivo: 'Intensivo',
  };
  return map[type] || type;
}

export function formatPrice(priceType: string, price: number, currency: string): string {
  if (priceType === 'Gratis') return 'Gratis';
  const symbol = currency === 'PEN' ? 'S/' : '$';
  const label = priceType === 'Mensual' ? '/mes' : priceType === 'Por clase' ? '/clase' : '';
  return `${symbol}${price}${label}`;
}

export function formatTimeSlots(slots: { days: string[]; startTime: string; endTime: string }[]): string {
  return slots.map(s => `${s.days.join(', ')} · ${s.startTime} – ${s.endTime}`).join(' | ');
}
